export const EXPERIMENT_ALERTS = {
  connectionMode: {
    dedupeKey: 'step-1-connection-mode',
    description: 'Drag nodes from apparatus to complete the circuit connections.',
    icon: '🔌',
    stepNumber: 1,
    target: '#circuit-panel',
    title: 'Connection Mode Activated',
    type: 'info',
  },
  circuitConnectionsCompleted: {
    description: 'The default wiring path has been placed on the apparatus.',
    icon: '✅',
    stepNumber: 1,
    target: '#circuit-panel',
    title: 'Circuit Connections Completed Successfully',
    type: 'success',
  },
  incorrectNodeConnection: {
    description: 'One or more wires are connected to the wrong node pair.',
    icon: '❌',
    stepNumber: 1,
    target: '#circuit-panel',
    title: 'Incorrect Node Connection Detected',
    type: 'error',
  },
  checkingConnections: {
    description: 'The lab console is validating each wire path.',
    duration: 2200,
    icon: '🎛️',
    stepNumber: 2,
    target: '#check-button',
    title: 'Checking Circuit Connections...',
    type: 'info',
  },
  connectionsVerified: {
    description: 'Connections verified. Follow the current experiment step.',
    icon: '✅',
    stepNumber: 2,
    target: '#resistance-controls',
    title: 'Right Connections',
    type: 'success',
  },
  connectionErrorFound: {
    icon: '⚠️',
    stepNumber: 2,
    target: '#circuit-panel',
    title: 'Connection Error Found - Please Recheck Wiring',
    type: 'error',
  },
  adjustResistance: {
    dedupeKey: 'step-3-adjust-resistance',
    description: 'Use the three resistance sliders before starting the supply.',
    icon: '🎛️',
    stepNumber: 3,
    target: '#resistance-controls',
    title: 'Adjust Resistance Values Using Sliders',
    type: 'info',
  },
  resistanceLocked: {
    description: 'Resistance controls are locked while the circuit is powered.',
    icon: '✅',
    stepNumber: 3,
    target: '#resistance-controls',
    title: 'Resistance Values Locked for Experiment',
    type: 'success',
  },
  powerOn: {
    description: 'The supply is now feeding the verified circuit.',
    icon: '⚡',
    stepNumber: 4,
    target: '#power-supply',
    title: 'Power Supply Turned ON',
    type: 'success',
  },
  cannotStartPower: {
    description: 'Run CHECK and correct the circuit wiring before powering the supply.',
    icon: '⚠️',
    stepNumber: 4,
    target: '#check-button',
    title: 'Cannot Start Power - Complete Connections First',
    type: 'warning',
  },
  adjustVoltage: {
    dedupeKey: 'step-5-adjust-voltage',
    description: 'Vary the supply voltage to obtain the required reading.',
    icon: '⚡',
    stepNumber: 5,
    target: '#voltage-control',
    title: 'Adjust Power Supply Voltage',
    type: 'info',
  },
  
 
  addingReading: {
    description: 'The measured value is being added to the observation table.',
    duration: 1800,
    icon: '📊',
    stepNumber: 6,
    target: '#observation-table-panel',
   title: 'Adding Reading To Observation Table',
    type: 'info',
  },
  readingAdded: {
    description: 'The reading has been successfully stored.',
    icon: '✅',
    stepNumber: 6,
    target: '#observation-table-panel',
    title: 'Reading Added Successfully',
    type: 'success',
  },
  readingAlreadyExists: {
    description: 'Change the voltage before recording another observation.',
    icon: '⚠️',
    stepNumber: 6,
    target: '#voltage-control',
    title: 'Reading Already Exists',
    type: 'warning',
  },
 
  preparingReport: {
    description: 'The print view is being prepared from the current observations.',
    duration: 2000,
    icon: '📊',
    stepNumber: 10,
    target: '#print-button',
    title: 'Preparing Experiment Report for Printing',
    type: 'info',
  },
  printLayoutGenerated: {
    description: 'The print dialog will use the generated experiment layout.',
    icon: '✅',
    stepNumber: 10,
    target: '#print-button',
    title: 'Print Layout Generated Successfully',
    type: 'success',
  },
  resettingSetup: {
    description:
'Confirm reset before all readings and connections are cleared.',
    duration: 1800,
    icon: '🎛️',
    stepNumber: 11,
    target: '#reset-button',
    title: 'Resetting Experiment Setup...',
    type: 'info',
  },
  resetWarning: {
    confirmLabel: 'OK',
    dedupeKey: 'step-11-reset-warning',
    description: 'Confirm reset before the current table and circuit are cleared.',
    icon: '⚠️',
    placement: 'center',
    requiresConfirmation: true,
    stepNumber: 11,
    target: '#reset-button',
    title: 'All Readings and Connections Will Be Cleared',
    type: 'warning',
  },
  resetSuccess: {
    description: 'The apparatus is ready for a fresh run.',
    icon: '✅',
    stepNumber: 11,
    target: '#circuit-panel',
    title: 'Experiment Reset Successfully',
    type: 'success',
  },
}
